spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipcode?createDatabaseIfNotExist=true
    username: root
    password: a
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        show_sql: true

management:
  endpoint:
    health:
      show-details: always